version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    env_file: database.env
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  postgres_data:
