"""empty message

Revision ID: 224c17423a57
Revises: 6a339d64bf7f
Create Date: 2019-09-14 19:51:52.240706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224c17423a57'
down_revision = '6a339d64bf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('league', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('back',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('variation', sa.String(length=64), nullable=True),
    sa.Column('overprint', sa.Boolean(), nullable=False),
    sa.Column('series_description', sa.String(length=64), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'variation', 'overprint', 'series_description')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'card_id')
    )
    op.create_table('variation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serieses',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('back_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['back_id'], ['back.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'back_id')
    )
    op.add_column('card', sa.Column('hof', sa.Boolean(), nullable=False))
    op.add_column('card', sa.Column('horizontal', sa.Boolean(), nullable=False))
    op.add_column('card', sa.Column('lipset_number', sa.Integer(), nullable=True))
    op.add_column('card', sa.Column('portrait', sa.Boolean(), nullable=False))
    op.add_column('card', sa.Column('pose', sa.String(length=64), nullable=True))
    op.add_column('card', sa.Column('team_name', sa.String(length=64), nullable=False))
    op.drop_column('card', 'variety')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('variety', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('card', 'team_name')
    op.drop_column('card', 'pose')
    op.drop_column('card', 'portrait')
    op.drop_column('card', 'lipset_number')
    op.drop_column('card', 'horizontal')
    op.drop_column('card', 'hof')
    op.drop_table('serieses')
    op.drop_table('variation')
    op.drop_table('teams')
    op.drop_table('back')
    op.drop_table('team')
    op.drop_table('series')
    op.drop_table('factory')
    # ### end Alembic commands ###
